apiVersion: v1
appVersion: 2.6.2
description: A Helm chart for sp-support
home: https://registry.ebanma.com
icon: https://hub.docker.com/public/images/logos/mini-logo.svg
maintainers:
- email: abc@126.com
  name: abc-haha
name: sp-support
sources:
- https://registry.ebanma.com
version: 5.1
