apiVersion: v1
appVersion: 2.6.2
description: A Helm chart for Docker Registry
home: https://hub.docker.com/_registry/
icon: https://hub.docker.com/public/images/logos/mini-logo.svg
maintainers:
- email: abc@126.com
  name: abc-haha
name: docker-registry
sources:
- https://github.com/docker/gistribution-library-images
version: 0.3.0